webapp/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hackathon123'

    from .routes import routes
    app.register_blueprint(routes , url_prefix = '/')

    return app

webapp/routes.py
from flask import Flask, jsonify , Blueprint, render_template, request
import json, requests
import numpy as np
#import boto3

# import geopandas as gpd

routes = Blueprint('routes', __name__)
CRASH_DATA_URL = 'https://data.sanjoseca.gov/api/3/action/datastore_search?resource_id=15408d78-9734-4ea1-b3e5-a0f99568dd9b&limit=5&q=title:jones' 
@routes.route('/crashes', methods=['GET'])
def get_crash_data():
    uResponse = requests.get(CRASH_DATA_URL)
    if uResponse.status_code == 200:
        data = uResponse.json()
    return jsonify(data)



# SAN_JOSE_API_URL = "https://geo.sanjoseca.gov/server/rest/services/OPN/OPN_OpenDataService/MapServer/549/query"

# def fetch_neighborhood_data():
#     params = {
#         "where": "1=1",
#         "outFields": "*",
#         "outSR": "4326",
#         "f": "json"
#     }
#     response = requests.get(SAN_JOSE_API_URL, params=params)
#     response.raise_for_status()  # Raise an error if the request fails
#     return response.json()

class Data:
   def __init__(self, neighborhood):
    self.neighborhood = []
    
class Neighborhood:
    def __init__(self, name, score):
        self.name = "Fowler Creek"
        self.score = 7.4

@routes.route("/neighborhood.html")
def neighborhood():
    nName = request.args.get('nName')

    
    # make request to bedrock with neighbor name
    # parse json request
    # return request as Neighborhood Class
    #return it  below VVVV
    return render_template("neighborhood.html", nName=nName, score=7)

@routes.route("/")
def index():
    return render_template("index.html")

# @routes.route("/api/neighborhoods")
# def get_neighborhoods():
#     data = fetch_neighborhood_data()

#     return jsonify(data)

@routes.route("/api/coordinates")
def get_coordinates():
    neighborhoods = []
    data = fetch_neighborhood_data()
    for feature in data.get('features', []):
        name = feature['properties'].get('name', 'Unknown')
        coordinates = feature['geometry'].get('coordinates',[])
        neighborhoods.append({'name':name, 'coordinates': coordinates})
    neighborhoods = neighborhoods.sort(key=lambda x: x['name'])    
    return(neighborhoods)

# @routes.route("/map")
# def createMap():
#     data = fetch_neighborhood_data()
    

webapp/templates/neighborhood.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
        <title>Livability</title>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"  integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="  crossorigin=""/> 
        <link href="../static/main.css" rel="stylesheet" />
    </head>
    <body>
        <header class="header">
            <div>
                <a class="head-title" href="{{url_for('routes.index')}}">
                    <img class="head-img" src="{{ url_for('static', filename='logo.png') }}" alt="">
                </a>
            </div>
        </header>
        <div id="map-container"></div>

        <main>
            
            <div class="main-flex">
                
                <div class="info-container">
                    <div class="neighbor-flex">
                        <div class="neighbor-name">{{nName}}</div>
                        <div class="neighbor-score">{{score}}</div>
                    </div>
            
                    <div>
                        <div class="trend-head">Trends</div>
                        <div class="trend-flex">
                            <!-- array of divs with trends -->
                            <div class="trend-item">
                                <div class="score-head">Livability Score</div>
                                <div class="score">7.5</div>
                                <div class="year-flex">
                                    <div class="year-item">
                                        <div class="year-head">+0.2</div>
                                        <div class="year">5 year</div>
                                    </div>
                                    <div class="year-item">
                                        <div class="year-head">-0.8</div>
                                        <div class="year">10 year</div>
                                    </div>
                                    <div class="year-item">
                                        <div class="year-head">-2.1</div>
                                        <div class="year">15 year</div>
                                    </div>
                                </div>
                            </div>

                            <div class="trend-item">
                                <div class="score-head">{ScoreType} Score</div>
                                <div class="score">{{score}}</div>
                                <div class="year-flex">
                                    <div class="year-item">
                                        <div class="year-head">{5}</div>
                                        <div class="year">5 year</div>
                                    </div>
                                    <div class="year-item">
                                        <div class="year-head">{10}</div>
                                        <div class="year">10 year</div>
                                    </div>
                                    <div class="year-item">
                                        <div class="year-head">{15}</div>
                                        <div class="year">15 year</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </main>
        <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

        <script>
            function getColor(score) {
                let green, red;
                if (score <= 5) {
                    red = 255;  
                    green = 255 - (5- score) * 51; 
                } else {
                    red = 255- (score - 5) * 51;
                    green = 255;   
                }
                const blue = 0;
                return `rgb(${red}, ${green}, ${blue})`;
            }
            let score = "{{score}}";
            let nName = "{{nName}}";
            const map = L.map('map-container',{
                center: [37.3382, -121.8863],
                zoom: 10.75,
                zoomSnap: 0,
                zoomDelta: 0.25,
                zoomControl: false,
                dragging: false,
                scrollWheelZoom: false,
                doubleClickZoom: false,
                boxZoom: false,
                keyboard: false,
                touchZoom: false,
            });

            L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
            }).addTo(map);

            const apiUrl = "https://geo.sanjoseca.gov/server/rest/services/OPN/OPN_OpenDataService/MapServer/549/query?where=1%3D1&outFields=*&outSR=4326&f=json";
            var polygon;
            // Fetch data from api 
            fetch(apiUrl)
                .then(response => response.json())
                .then(data => {
                    // add polygons
                    data.features.forEach(feature => {
                        if(feature.attributes.NAME != nName){
                            return;
                        }
                        const coords = feature.geometry.rings[0].map(coord => [coord[1], coord[0]]);
                        polygon = L.polygon(coords, {
                            color: getColor(score),
                            fillOpacity: 0.5,
                        }).addTo(map)
                        
                    });
                    const center = polygon.getBounds().getCenter();
                    console.log(center);
                    map.setView(center, 10.75);
                    const bounds = polygon.getBounds();
                    map.fitBounds(bounds);

                })
                .catch(error => console.error('Error fetching data:', error));
        </script>
    </body>
</html>